### ISSUE TITLE
Error trying to install Ogone version 0.16.0-rc.7 from nest.land

### ISSUE THREAD

**Issue by buttercubz** [SRNV/Ogone#5]
I am part of the [Trex](https://github.com/crewdevio/Trex) development team and we are adding nest.land as our official package registry and testing using Ogone this installation fails.

**Comment by buttercubz** [comment]
https://github.com/SRNV/Ogone/blob/8cf79e0d4c180ec6bef86079df68b821e8ac7f3d/src/ogone/compilation/inspection/styles.ts#L2

that part is causing the problem

**Comment by littledivy** [comment]
@buttercubz This looks like an issue with deno-sass or the import done by Ogone.

**Comment by buttercubz** [comment]
the error says that you could not import from the **src /ogone/compilation/inspection/styles.ts** file and that the error occurs on line 2

**Comment by littledivy** [comment]
@buttercubz Created a PR that imports Sass from deno.land/x. Please do check if it works after merging.

**Comment by littledivy** [comment]
@buttercubz `0.16.0-rc.8` should fix this issue.
